version: "3"

services:
  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    restart: always
    environment:
      - TZ=UTC
      - GENERIC_TIMEZONE=UTC
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data:
